[project]
name = "package_1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "transformers>=4.48.1",
  "torch-directml>=0.2.1",
  "optimum>=1.17.0",               # Optimum library for ONNX support
  "onnx>=1.8.0",                  # ONNX library
  "onnxruntime>=1.8.0",           # Ensure ONNX Runtime is at least version 1.8.0
  "onnxruntime-directml>=1.8.0",  # ONNX runtime with DirectML support
  "onnxruntime-extensions>=0.7.0",
  #"onnxruntime-quantization
  "pathlib>=1.0.0",               # Pathlib for handling paths
  "accelerate>=0.21.0",
  "librosa==0.9.2",
  "datasets==3.5.0"
]

# Specify the package builder
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Tell Hatchling to include the package_1 folder as a package
[tool.hatch.build]
include = ["packages/package_1"]

# manage the environment like a package rather than a standalone virtual environment
[tool.uv]
package = true